angular.module('phpdraft.draft', [
  'ngRoute',
  'angular-flipclock',
  'darthwade.loading',
  'dndLists',
  'mgcrea.ngStrap.affix',
  'mgcrea.ngStrap.helpers.debounce',
  'mgcrea.ngStrap.helpers.dimensions',
  'ngLodash',
  'ordinal',
  'slip',
  'toggle-switch',
  'ui.bootstrap',
  'phpdraft.shared',
  'phpdraft.pick',
]);
