angular.module('phpdraft', [
  // 'ngAnimate',
  // 'ngResource',
  // 'ngRoute',
  'ngSanitize', // TODO: maybe keep this one on app?
  // 'angular-flipclock',
  // 'angularMoment',
  // 'darthwade.loading',
  // 'datatables',
  // 'dndLists',
  // 'mgcrea.ngStrap.affix',
  // 'mgcrea.ngStrap.helpers.debounce',
  // 'mgcrea.ngStrap.helpers.dimensions',
  // 'ngCapsLock',
  // 'ngFileUpload',
  // 'ngLodash',
  // 'ngMask',
  // 'ngStorage',
  // 'ordinal',
  // 'slip',
  // 'toastr',
  // 'toggle-switch',
  // 'ui.bootstrap',
  // 'validation.match',
  // 'vcRecaptcha',
  //TODO: Begin showing app-level angular modules here
  'phpdraft.config',
  'phpdraft.env',
  'phpdraft.shared',
  'phpdraft.home',
  'phpdraft.navigation',
  'phpdraft.authentication',
]);
